### PR TITLE
Bottommenu pausemenu bug

### PR DESCRIPTION
**Pull request by Exairnous**
fixes a couple problems with the pause menu and makes it more like diablo's

### CODE REVIEW

**Comment by wheybags** [comment]
What exactly is this patch supposed to do? It seems I can click on the bottom menu buttons while the game is paused and it will unpause? Is this what it was meant to do?

**Comment by Exairnous** [comment]
Yes.  This patch does a couple things, for one it makes the pause menu act in mostly the same way as the original Diablo (the behaviour you noted);  in Diablo the char screens stay up and the menu actually covers them, but given that this is already a major change I didn't want to go to far.  The pause menu also had a nasty bug where if you clicked outside the menu it would lose focus and under the right conditions if you pressed ESC it would end up that the game unpaused but the menu didn't disappear; this is now fixed.

**Comment by wheybags** [comment]
I'm all for the bug fix, but not a fan of having the bottom menu usable through the pause menu unfortunately :s.
Any chance you could open a new PR with just the bugfix?

**Comment by Exairnous** [comment]
That's the way it is in the original Diablo, but I'll be glad to isolate just the bugfix and re-upload it.  Should be done in a couple of days or less; if it isn't just poke me again :)

**Pull request closed without merging**
