### PR TITLE
Reduce components visibility #469

### PR DESCRIPTION
**Pull request by akuskis**
This one should reduce visibility of freeablo/components, to fix issue #469

### CODE REVIEW

**Comment by wheybags** [comment]
Would it be a better solution to just rename our header to fa_audio.h or something like that?

**Comment by akuskis** [comment]
If you are fine with that, then I can rework it.
Why I didn't rename it and only reduced scope, because there can be other situations like this.

**Comment by wheybags** [comment]
Well, even with the reduced scope, it can still happen that there is a collision in a module that actually needs both headers. We should be making sure our header names are un-generic enough that they're unlikely to cause collisions.

**Comment by akuskis** [comment]
Updated

**Comment by wheybags** [comment]
Cool, thanks!

**Pull request merged**
