### PR TITLE
Use pushdown state-machine to handle actor state

### PR DESCRIPTION
**Pull request by Fuco1**
The code is still hairy and I used some hacks like friend classes (for now) to enable the first round of refactoring.

Next steps will be to move all the behaviour to their own states and define proper interface to talk to the actor.

So far there is only the "BaseState" (which will turn abstract eventually) doing all the work old `Actor::update` was doing except handling the attack state, I have added a state for that as an example of how simple it can be :)

### CODE REVIEW

**Comment by wheybags** [comment]
I like the idea in principle, can you explain how it works/will work in practice? Also, it seem you've got some link errors on windows, according to appveyor

**Comment by Fuco1** [comment]
It's based somewhat loosely on combination of ideas from this article: http://gameprogrammingpatterns.com/state.html It's a nice read so you might want to read it anyway.  It explains it very well.

Basically it is a [pushdown automaton](https://en.wikipedia.org/wiki/Pushdown_automaton).  Every state is a class with an update method which can return optionally a new state or nothing (then it remains in that state).  Additionally to the returned state you specify one of the three operations: pop, push, replace.  

With these you control the "stack" of state scripts.  This is super helpful as it allows us to remember where we came from (i.e. on top of the standard FSM we have a notion of history through the stack).  So I can simply change states as usual with replace or I can push a new state, then do some stuff in it and then the state can pop itself off and the actor returns to whatever they were doing previously.

An example can be a creature that wanders around or does some other business, but when the player approaches it switches to a "flee" state.  When they are far enough the state pops itself and the creature reverts to whatever they were doing before.

**Comment by wheybags** [comment]
Link error on windows is because there's no .cpp files in StateMcahine component. If you add a dummy empty cpp file in there, then it should link fine

**Comment by wheybags** [comment]
Ready for merge? I'm happy to merge now if you are

**Comment by Fuco1** [comment]
@wheybags  Yep.  I'll integrate the other branches with this when merged (there have been some conflicts in the `Actor::update` method) and then we can continue refactoring the updates into separate states.

**Comment by wheybags** [comment]
Cool, and thanks again!

**Pull request merged**
