### PR TITLE
Fix fullscreen setting not being read correctly.

### PR DESCRIPTION
**Pull request by rohit-n**

### CODE REVIEW

**Comment by konopka90** [comment]
@gbudny I think that your problem is related to other issue, something with menu rendering. Does this problem exist also in build from master branch with/without fullscreen? 

Anyway, PR works good, can be merged.

**Comment by konopka90** [comment]
@gbudny In file https://github.com/wheybags/freeablo/blob/master/apps/freeablo/engine/enginemain.cpp in line 72 add   
``` 
Render::updateGuiBuffer(NULL);
``` 
and please tell me if it helps.

**Comment by gbudny** [comment]
@gbudny

This issue exists in builds from all branches in the with/without fullscreen mode.

I added this line, but it did not help me to solve this issue.

**Comment by wheybags** [comment]
Works fine here (on osx), so I'll merge, sorry for the delay.
@gbudny that issue seems unrelated to this patch, but still worrying.
Is it still happening to you?

**Comment by gbudny** [comment]
I checked this new version of Freeablo, and I have the same issue on Mac OS X.

**Pull request merged**
