### PR TITLE
Loading and rendering original Diablo-fonts

### PR DESCRIPTION
**Pull request by konopka90**
Hi, i added two things: 
1. Image in background in main menu
2. Loading and rendering original Diablo-fonts from MPQ. 

Example in RML: 
            div#version
            {
                icon-decorator: fatext;
                icon-text: Freeablo v1.0;
                icon-size: 24;    // available 16,24,30 and 42
                icon-style: gray;   // available: gray or normal font
            }

I had no time to reimplement main menu, just added game version at the bottom.

### CODE REVIEW

**Comment by wheybags** [comment]
Hi, sorry for the delay, just moved house and I haven't had internet access.
This looks cool, but it doesn't go through the librocket font rendering, which would probably cause problems. There is a pull request to librocket: https://github.com/libRocket/libRocket/pull/34 which would allow bitmap fonts of this sort, could you maybe adapt this code to use that?
The pr is pretty outdated though, it'd have to be fixed up to work against the latest master.

**Comment by konopka90** [comment]
Ok, I didn't know there is interface for rendering fonts, thanks for tips. I'll try to implement it soon.

**Comment by konopka90** [comment]
I looked at pull request to librocket , so far it is really hard to write and test code with this feature. As u said it's outdated. I tried to combine it with Freeablo but it was impossible due too many differences in librocket API. What we are going to do now ?

**Comment by wheybags** [comment]
That pr needs to be merged into the latest master of libRocket, which admittedly would be a giant pain in the ass. I was planning on doing that at some point, but if you want to instead that would be really cool.
Your time might be better spent working on some other feature, there's a list of features for v0.3 here: https://github.com/wheybags/freeablo/milestones/v0.3 , if you're interested.
The launcher one would be good, plan was to make a config file that points to the location of Diablo.exe and DIABDAT.mpq, and the launcher would generate that config on first run.

Thanks very much for taking the time to contribute btw!
It's nice to see a new contributor.
I'm gonna be working on a sound framework now today, been too long since I got off my ass and wrote some code :p

**Comment by konopka90** [comment]
Ok I leave fonts, actually launcher is in progress.

**Pull request closed without merging**
