### PR TITLE
Hello my friend, stay a while and listen!

### PR DESCRIPTION
**Pull request by konopka90**
Basic mechanism for dialogues 
+ Opening dialogue
+ Playing sound

Go to the story teller or smith and click on him!

### CODE REVIEW

**Comment by wheybags** [comment]
When the dialogue menu opens, it opens at the top left of the screen. Maybe the middle of the screen would be better?
It's fine if it blocks access to all other ui, iirc it does in diablo as well

**Comment by konopka90** [comment]
Yes, I will try to do it as in D1 - show dialogue menu on right side of screen. And if dialogue menu opens then GUI with stats/spells etc. will hide.

**Comment by konopka90** [comment]
Someone can review and I will go further

**Comment by konopka90** [comment]
Dialogues block input to gui now like in D1. You can check it now.

**Comment by wheybags** [comment]
Cool, looks good!

**Pull request merged**
