### PR TITLE
Complete selling implementation + some small fixes.

### PR DESCRIPTION
**Pull request by Predelnik**
1. Completed selling filters and confirmation dialog.
2. Walking through stairs is probably temporary solution and technically they should be more than one tile in size, but I think that it's still important for them to work at least this way for now.
3. Fix for character look not updating to dungeon sprites when in dungeon.

### CODE REVIEW

**Comment by stavrossk** [comment]
Hi, is Freeablo playable at it's current state?

Thanks,
Stavros.

**Comment by wheybags** [comment]
Nope, not really, but getting close

**Comment by stavrossk** [comment]
@wheybags Thanks, can't wait to play Diablo on my modern computer!

**Comment by Hydroque** [comment]
@stavrossk There are CD patches available so that you can play and you'll need a fixed directx dll iirc. Although, for freeablo, you'd already have to meet the requirement as it uses its copyrighted resources, but doesn't distribute.

**Pull request merged**
