### PR TITLE
try fix issule#247(RAII IO)

### PR DESCRIPTION
**Pull request by pengyz**
fix for #247:
1. add **FAFileObject** class for RAII wrapper of the original C style  FAIO functions.
2. Change all callers to use the new wrapper besides the **FAIOFileInterface**(it can just use the original c style io  functions).

### CODE REVIEW

**Comment by pengyz** [comment]
On, I will fix the compile warnings since the vs don't give me it.

**Comment by wheybags** [comment]
Basically looks good! Just one issue is that you used literal tabs in a few places, whereas the rest if the project uses 4 spaces for indentation. If that's fixed then I think I'm happy to merge.

**Comment by pengyz** [comment]
ok，it's just a auto format by the visual studio. I'll fix it.

**Comment by wheybags** [comment]
Great, thanks!
Sorry for the delay

**Pull request merged**
