### PR TITLE
New celviewer

### PR DESCRIPTION
**Pull request by konopka90**
New features:
- render window in application
- dockable windows
- find file box

Works on Ubuntu 15.04. Please check if it's working on other platforms.

screenqnq

### CODE REVIEW

**Comment by konopka90** [comment]
Qt >= 5.4 required

**Comment by konopka90** [comment]
Qt >= 5.1

**Comment by gbudny** [comment]
I tried to run it on Mac, but I have issues with celview:

./celview 
Segmentation fault: 11

https://gist.github.com/gbudny/af77b41afc65c1528cbba5724c168787

**Comment by konopka90** [comment]
As I expected. SDL complicates the task.

**Comment by wheybags** [comment]
On windows:

```
Settings file "E:/freeablo-vs15/freeablo-windows-build/build/Debug/celview.ini"
does not exists. Creating file...
WindowCreationData::create: CreateWindowEx failed ()
ASSERT: "platformWindow" in file kernel\qwindow.cpp, line 396
```

Call stack:
```
 	Qt5Cored.dll!668a5911()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for Qt5Cored.dll]	
 	Qt5Cored.dll!668a59e6()	Unknown
 	Qt5Cored.dll!668a45dd()	Unknown
 	Qt5Cored.dll!6689b2b3()	Unknown
 	Qt5Guid.dll!0165f5ef()	Unknown
 	Qt5Guid.dll!0165bbde()	Unknown
 	Qt5Guid.dll!0165bc4c()	Unknown
>	celview.exe!MainWindow::loadSettings() Line 67	C++
 	celview.exe!MainWindow::MainWindow(QWidget * parent) Line 34	C++
 	celview.exe!SDL_main(int argc, char * * argv) Line 8	C++
 	[External Code]	
```

**Comment by konopka90** [comment]
Im afraid that without raw opengl backend ( instead of sdl backend )  it is impossible to do.

**Comment by wheybags** [comment]
Is there any need to use sdl or any graphics api for that matter?
Couldn't we just copy the image data to a QImage for display?

**Comment by konopka90** [comment]
There is no need ofc, I gave up too early. Good idea, thx.

**Comment by wheybags** [comment]
closed in favour of #296

**Pull request closed without merging**
