### PR TITLE
CEL & CL2 new decoding implementation

### PR DESCRIPTION
**Pull request by konopka90**
Omg I did it. What is done:
   - Correct decoding cel & cl2
   - Nice class CelDecoder design prepared for further development
   - New resource files cl2.ini and cel.ini

To do: 
   - Loading and handling TRN files
   - Handling rest of PAL files
   - Better getImageInfo (don't read all frames to get w/h of image)

So far I found two bugs:
1) Something is wrong with algorithm responsible for loading level tiles. Problem probably can be solved in function `decodeFrameType2or3` , @mewmew  could you look at this ? Maybe you will find quick solution :)
s1

2) Something happened to FreeabloWhite11 font but in celview application everything is OK, maybe problem is with librocket and configuration file for this font: 
s2

Many thanks to @mewmew for blizzconv project.
Happy lecture !

### CODE REVIEW

**Comment by mewmew** [comment]
> Something is wrong with algorithm responsible for loading level tiles. Problem probably can be solved in function decodeFrameType2or3 , @mewmew could you look at this ?

It is quite likely that there is simply a transparent line missing, or being added when it shouldn't be. We also had this problem in blizzconv some years ago. I'll take a closer look, once the exams are finished : )

> Many thanks to @mewmew for blizzconv project.

Glad you found a good use for it : ) Just for the record, blizzconv has been a joint effort between @7i, @karlek and myself, and of course building upon the accumulated knowledge of the d1 community at large, with some incredible work being done by [The Dark](http://www.thedark5.com/) and Jarulf.

**Comment by konopka90** [comment]
In last commit for frames of type 2,3,4 and 5 in I used old implementation and it seems that it is almost good now, some minor bugs occurs e.g.:

s1
s2

**Comment by mewmew** [comment]
@konopka90, I get the following error when trying to compile your [cel](https://github.com/konopka90/freeablo/tree/cel) branch of Freeablo. Which step did I miss?

```
Scanning dependencies of target fontgenerator
[ 96%] Building CXX object apps/fontgenerator/CMakeFiles/fontgenerator.dir/main.cpp.o
In file included from /home/u/Desktop/freeablo/apps/fontgenerator/main.cpp:4:0:
/home/u/Desktop/freeablo/components/misc/disablewarn.h:7:40: warning: ‘-pedantic’ is not an option that controls warnings [-Wpragmas]
         #pragma GCC diagnostic ignored "-pedantic"
                                        ^~~~~~~~~~~
/home/u/Desktop/freeablo/apps/fontgenerator/main.cpp: In function ‘void help(char**)’:
/home/u/Desktop/freeablo/apps/fontgenerator/main.cpp:10:5: error: ‘cout’ is not a member of ‘std’
     std::cout << argv[0] << " mpq_path " << std::endl;
     ^~~
/home/u/Desktop/freeablo/apps/fontgenerator/main.cpp:11:5: error: ‘cout’ is not a member of ‘std’
     std::cout << std::endl << "Application generates part of libRocket font file." << std::endl;
     ^~~
/home/u/Desktop/freeablo/apps/fontgenerator/main.cpp: In function ‘int main(int, char**)’:
/home/u/Desktop/freeablo/apps/fontgenerator/main.cpp:102:9: error: ‘cout’ is not a member of ‘std’
         std::cout << mapping[i] << std::endl;
         ^~~
apps/fontgenerator/CMakeFiles/fontgenerator.dir/build.make:62: recipe for target 'apps/fontgenerator/CMakeFiles/fontgenerator.dir/main.cpp.o' failed
make[2]: *** [apps/fontgenerator/CMakeFiles/fontgenerator.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:958: recipe for target 'apps/fontgenerator/CMakeFiles/fontgenerator.dir/all' failed
make[1]: *** [apps/fontgenerator/CMakeFiles/fontgenerator.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
```

**Comment by konopka90** [comment]
Which compiler do you use ? Try now.

**Comment by mewmew** [comment]
> Which compiler do you use ? Try now.

Thanks, now the build succeeds.

```
u@x1 ~> gcc --version 
gcc (GCC) 6.1.1 20160501
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

u@x1 ~> clang --version
clang version 3.8.0 (tags/RELEASE_380/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by mewmew** [comment]
Looking good! Glad you manged to fix 1). It seems like 2) is still broken?

Freeablo screenshot after cel rewrite

**Comment by konopka90** [comment]
2) is fixed also. Did you notice any issue with 2)?

**Comment by wheybags** [comment]
Get better soon!
Also, this looks really great!
The results aren't perfect yet:
```
439/1402 files succeeded, 31.3124%
21393/110110 frames succeeded, 19.4288%
```

but they're a damn sight better than what we had before!

**Comment by wheybags** [comment]
Also re: the tiny corner in griswold's house, that triangle is actually transparent in the assets, it's blizzard's bug not yours :p

**Pull request merged**
