### PR TITLE
Banner for launcher + icons for options

### PR DESCRIPTION
**Pull request by konopka90**
Check if you like it :)
For now I don't have any icon for option Graphics.

yup

### CODE REVIEW

**Comment by gbudny** [comment]
The launcher looks great.

However, I noticed some warnings on Mac when I try to run the launcher:

./launcher
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile

**Comment by Exairnous** [comment]
Looks good.  If you're still looking for a graphics icon, maybe the red highlighted one from bnbuttns.pcx in the folder ui_art from diabdat.mpq  would work.
spectacle t22731

**Comment by konopka90** [comment]
@gbudny oh, I will remove the iCCP chunk from the PNG images, warning should disappear. 

@Exairnous looks good but as you said there can be problem with license.  Maybe simple icon of LCD display will do.

**Comment by konopka90** [comment]
@gbudny Please check if there are still warnings.

**Comment by gbudny** [comment]
Thanks.

I checked the new version of the launcher, and I don't see this warning on Mac OS X.

**Comment by Exairnous** [comment]
@ konopka90 Although, technically you're using game art in the banner so maybe using game art for icons is acceptable?

**Comment by konopka90** [comment]
Ok, please send me transparent icon, i will replace it. What do you think about Play icon - is it ok ?? 
@wheybags What do you think about using icon from game assets in launcher in terms of license?

**Comment by Exairnous** [comment]
I've attached the icon to this comment, if you want me to send it to you in a different way, let me know.
I've also included two mockups one with the sword and helmet icon the other with the screen and keyboard.  Each of them have the play pentagram rotated so the tip is pointing right like traditional play icons.  Let me know what everyone thinks.
bnbuttns_horned_helmet
freeablo_launcher_1
freeablo_launcher_2

**Comment by konopka90** [comment]
Thanks I think it looks great ! I have also idea about word "freeablo" - maybe it is possible to replace static pentagram with rotating pentagram - like on http://freeablo.org . I will try some experiments.

**Comment by Exairnous** [comment]
Sounds good.

**Comment by wheybags** [comment]
I'd prefer to use the standard screen icon, not something from the game assets (although the icon you picked does look good)

**Comment by konopka90** [comment]
I rotated play icon and decided to finish for now with launcher so it's ready to merge.

**Comment by wheybags** [comment]
The hilighting looks a bit weird on osx, but ehh, osx :p

screen shot 2016-04-11 at 9 52 33 p m

**Pull request merged**
