### PR TITLE
GUI for console

### PR DESCRIPTION
**Pull request by konopka90**
Hi, maybe it is too early for this feature but I made simple GUI for console. For now it launches everywhere except main menu.
   - Fixed height 600px
   - Show/hide under ~
   - Accept commands and adds to visible area
   - Arrow up - show previous command in input
   - Arrow down - show next command in input

### CODE REVIEW

**Comment by wheybags** [comment]
Looks good so far, but ofc it doesn't actually do anything yet.
Could you make it so it just functions as a python shell?
If you don't want to yet, that's fine, we can add that in later.

**Comment by wheybags** [comment]
Oh, also, could you make it pass key events through to the base rml when its hidden? like https://github.com/wheybags/freeablo/blob/master/resources/gui/bottommenu.rml#L76

(currently if you open + close console, then press esc, it will not pause, as the key events still go to the console)

**Comment by konopka90** [comment]
Ok i will experiment this week

**Comment by konopka90** [comment]
Key events and python shell works properly. Added shortcuts for quit/pause/unpause/load game/save game in console (just type f.e. "quit" and press enter").

**Comment by wheybags** [comment]
Cool, looks great, just one last nitpicky thing I noticed is printing newlines, eg: print "asasd\nadasd", it will just print a space where the newline should be.

**Comment by konopka90** [comment]
Yup, also there's problem with multiline output. Resize window to ~400px x 800px and type command "freeablo.quit(1,2)" :3

**Comment by konopka90** [comment]
Please check if everything is good. In the future I'm gonna to add auto-complete feature.

**Comment by konopka90** [comment]
Autocomplete feature delivered.

**Pull request merged**
