### PR TITLE
GUI for Single player creator

### PR DESCRIPTION
**Pull request by konopka90**
Character creator added:
+ select hero menu
+ select class menu
+ enter name menu
+ invalid name screen

\+Main menu display fix.

### CODE REVIEW

**Comment by wheybags** [comment]
when i select create a new character, it will always tell me i entered an invalid name.
Also, the invalid name menu has an "ok" option, that i can only select by clicking, hitting enter doesn't work

**Comment by konopka90** [comment]
Yes, there is still no validation, i dont know how diablo validates name but it's not important for now. What is odd it says that you cannot use space but.. you can :)

**Comment by wheybags** [comment]
Was that last commit supposed to fix the issues I described?
Just checked and it's still there

**Comment by konopka90** [comment]
> Was that last commit supposed to fix the issues I described? 

No, i didn't read it before commit. Please check now.

**Comment by wheybags** [comment]
lgtm

**Pull request merged**
