### PR TITLE
Fix markdown header

### PR DESCRIPTION
**Pull request by danyshaanan**

### CODE REVIEW

**Comment by afritz1** [comment]
There are some other places in the Readme with the same problem. You should add those to your pull request, too. I was going to do it myself, but I saw that you already started it!

**Comment by danyshaanan** [comment]
@afritz1 Right! I've went through all the markdown file and fixed whatever I could find. (mainly headers and code snippets formatting).

**Comment by wheybags** [comment]
Nice, thanks!
Did GitHub change how they format markdown? All those headers used to work fine with no space after the #. Same thing happened to the readme of our private repo at work.

**Comment by danyshaanan** [comment]
Yeah, I've seen this before. Don't know if they changed how they format it. [Only git will tell](https://github.com/github/markup).

**Pull request merged**
