### PR TITLE
New font Freeablo in all menus

### PR DESCRIPTION
**Pull request by konopka90**

### CODE REVIEW

**Comment by wheybags** [comment]
Nice!
Just one issue I can see for now, the W in the screenshot below, you can see the next glyph peeking in at the right
screenshot from 2015-09-26 16-56-44

**Comment by konopka90** [comment]
Fixed. One more issue - this menu looks different on my pc. Pentagrams are inline with text, did you change anything in your build ? 

diff

**Comment by wheybags** [comment]
Nope, nothing. Even just tried deleting my settings-user.ini there

**Comment by konopka90** [comment]
Not so good, it sounds like there are differences in librocket on Windows and Linux build.

**Comment by wheybags** [comment]
My screenshot was from Linux, was yours?

**Comment by konopka90** [comment]
Yes, mine was from Linux too

**Comment by sheepo99** [comment]
To be fair, I'd prefer to have a new font created from scratch altogether, so we could finally have expanded Latin/Russian/Greek characters. This would allow us to finally translate the game to other languages, which would be an interesting addition to Freeablo.

**Comment by wheybags** [comment]
merged it, I suspect the issue is just related in general to ui scaling, and it works fine on another computer that I'm using fro development atm

**Pull request merged**
