### PR TITLE
fixed explanation of building process in readme.md

### PR DESCRIPTION
**Pull request by akuskis**
We are already in "freeablo/build" folder, that is why "../freeablo" cause errors.

### CODE REVIEW

**Comment by tilkinsc** [comment]
Great! I am going to do a test build to see if I can build.

**Comment by tilkinsc** [comment]
So I couldn't get it to build because there was some errors due to not being able to find some functions, and it looks like boost doesn't build well either. windows7, gcc 7.3.0, mingw64, and this was a fresh install.

**Comment by akuskis** [comment]
This PR just fix mistakes in "readme.md".
Take a look at a comment to this PR.

**Comment by wheybags** [comment]
Been meaning to d this for ages, thanks

**Comment by tilkinsc** [comment]
But that involves giving my PC microsoft aids

**Comment by wheybags** [comment]
Then use linux. Sorry, but I don't normally use windows myself, if someone wants to add support for building with mingw, I'd accept a pr, but it's not exactly a priority :p

**Pull request merged**
