### PR TITLE
various performance improvements

### PR DESCRIPTION
**Pull request by wheybags**

### CODE REVIEW

**Comment by wheybags** [comment]
28 -> 60fps on borrowed work macbook \o/
Also the game loop doesn't overrun it's allocated time anymore (it was doing that... a lot...)

**Comment by konopka90** [comment]
Oops, something is wrong, commit b2c9d119e3211a147c8569817c8bd84e09c3779d is not so good :>
something_wrong

**Comment by wheybags** [comment]
@konopka90 that patch should fix it

**Comment by konopka90** [comment]
Nice, merge

**Pull request merged**
