### PR TITLE
Path finding based on A* algorithm

### PR DESCRIPTION
**Pull request by konopka90**
I created implementation of A\* algorithm and sample program with few testcases. Interface "Level" is similar to original class "Level" so it will be easy to adopt this solution. In my opinion it works quite good and fast. For now I have to add cost checking - diagonal vs non-diagonal move. Regarding algorithm if user selects unreachable location it will find closest point and path for this location.

Remarks: works only with C++11.
Reference: http://www.redblobgames.com/pathfinding/a-star/implementation.html#cplusplus

### CODE REVIEW

**Comment by wheybags** [comment]
looks good so far, will be happy to merge once it's integrated into the main codebase.
I had to do a few things to make it compile on windows.
Diff below:
```
diff --git a/apps/findpath/main.cpp b/apps/findpath/main.cpp
index d35e880..5f2fc83 100644
--- a/apps/findpath/main.cpp
+++ b/apps/findpath/main.cpp
@@ -10,6 +10,7 @@
 #include <iomanip>
 #include <algorithm>
 #include <chrono>
+#include <string>
 
 using namespace std::chrono;
 using namespace std;
@@ -99,7 +100,7 @@ ostream& operator<<(ostream& os, FindPath::Location & location )
     return os;
 }
 
-void drawPath(Level::Level& graph, int field_width,
+void drawPath(::Level::Level& graph, int field_width,
                unordered_map<FindPath::Location, int>* distances=0,
                unordered_map<FindPath::Location, FindPath::Location>* point_to=0,
                vector<FindPath::Location>* path=0)
@@ -147,7 +148,7 @@ void drawPath(Level::Level& graph, int field_width,
 
 int main()
 {
-    Level::Level * level = new LevelImpl();
+    ::Level::Level * level = new LevelImpl();
     FindPath findPath(level);
 
     FindPath::Location start,goal;
diff --git a/components/level/findpath.h b/components/level/findpath.h
index 2803fac..d044002 100644
--- a/components/level/findpath.h
+++ b/components/level/findpath.h
@@ -11,8 +11,9 @@
 #include <queue>
 #include <iomanip>
 #include <algorithm>
-#include <tr1/unordered_map>
-#include <tr1/unordered_set>
+#include <unordered_map>
+#include <unordered_set>
+#include <functional>
 
 
 
@@ -20,7 +21,7 @@ using namespace std;
 using namespace tr1;
 
 namespace std {
-namespace tr1 {
+//namespace tr1 {
 
     template <>
     struct hash<pair<int,int> > {
@@ -31,7 +32,7 @@ namespace tr1 {
             return x * 1812433253 + y;
         }
     };
-}
+//}
 }
 
 template<typename T, typename Number=size_t>
```

**Comment by wheybags** [comment]
*bump*
:p

**Comment by konopka90** [comment]
i got better cookie for you, just wait

**Comment by konopka90** [comment]
Can someone look at this ? Algorithm looks fine but I have to admit that I don't know how to use it properly. I tried two times but always I had some problems...

**Comment by pengyz** [comment]
I try to merge it. see #249

**Pull request closed without merging**
