### PR TITLE
Celview 

### PR DESCRIPTION
**Pull request by konopka90**
Hi, I made simple GUI for celview. Please let me know if you like it. If yes tell me what features in GUI you want - I will add it. 
I think about:

     - start / stop animation
     - information: number of frames in group, current index of visible frame
     - buttons for navigation : previous frame / next frame
     - availability of changing background color

### CODE REVIEW

**Comment by konopka90** [comment]
Ref: * #40

**Comment by wheybags** [comment]
Sorry it took so long to get to this. It's looking really great!
In addition to the things you mentioned, I'd add a few:
```
- save / load listfile and mpq locations from the game config file
- export png sequence
- set palette file (a small number of cel files don't use the default palette)
- replace tabs with spaces (tabs are the preferred indentation for this project)
- draw the sprite within the qt window (can leave this one for now, it's just a pain, we can deal with it later when an editor of some form is being made)
```
I'm happy to merge now, once the tabs are changed (or I can do that myself)

**Comment by konopka90** [comment]
"replace tabs with spaces (tabs are the preferred indentation for this project)"

So there should be tabs or spaces ? ;p

**Comment by mewmew** [comment]
> "replace tabs with spaces (tabs are the preferred indentation for this project)"
>
> So there should be tabs or spaces ? ;p

Lovely unambiguity :) It should of cause be "replace spaces with tabs".

**Comment by wheybags** [comment]
Lol I'm an idiot.
4 spaces, as per the openmw coding standards :p

**Comment by konopka90** [comment]
New features!

   - Change background in render window
   - Export single CEL/CL2 to PNG
   - Export all CEL/CL2 files from MPQ to PNG files
   - Start/stop animation
   - Some improvements for loading proper PAL file
   - Tabs replaced with spaces

**Pull request merged**
